### ISSUE TITLE
Add package to https://gap-packages.github.io/ 

### ISSUE THREAD

**Issue by olexandr-konovalov** [jesselansdown/EigenGap#1]
@jesselansdown We maintain a list of GAP packages with their public repositories at https://gap-packages.github.io/ - would you like this package to be listed there? It's not limited to packages redistributed with GAP - the aim is to list all packages independently of their status. This will help other GAP users and developers to find them.

**Comment by jesselansdown** [comment]
Hi @alex-konovalov. Sure, that sounds good to me! I still need to fix documentation and a few other things for this package etc... but I guess that is ok? I also have two other GAP packages, Gurobify and AssociationSchemes, which are more developed. Would you like to list those as well? Links to them can be found here: http://www.jesselansdown.com/Software/

**Comment by olexandr-konovalov** [comment]
Thanks - yes, that's fine! Done in https://github.com/gap-packages/gap-packages.github.io/commit/9e0f609fc2be0012fdb916a485066bb8a96b5fce for this and the two other packages - thanks for letting me know about them!
