### ISSUE TITLE
Potential GC crashes

### ISSUE THREAD

**Issue by fingolfin** [jesselansdown/EigenGap#3]
A colleague made me aware of this repository, and I had a peek out of curiosity, and noticed a few things. One is that your kernel extension may occasionally crash due to code like this:
```gap
  Obj eigenvalues = NEW_PLIST(T_PLIST, dimension);
  SET_LEN_PLIST(eigenvalues, dimension);
  for (i = 0; i < dimension; i = i+1){
    SET_ELM_PLIST(eigenvalues, i+1, NEW_MACFLOAT(es.eigenvalues().col(0)[i]));
  }
```
The problem is that you are creating new objects via `NEW_MACFLOAT`, but the only references to that are stored in a plist which is older. Now, if a GC is triggered twice while the above code runs, then any of the float objects added between the first and second GC will be collected, yet (now invalid) references to those will be retained.

To fix this, you could insert appropriate `CHANGED_BAG` calls after the `SET_ELM_PLIST` calls. But I'd suggest to instead not use low-level (dangerous) APIs and instead use their safe high level counterparts. I.e.
```gap
  Obj eigenvalues = NEW_PLIST(T_PLIST_EMPTY, dimension);
  for (i = 0; i < dimension; i++){
    ASS_LIST(eigenvalues, i+1, NEW_MACFLOAT(es.eigenvalues().col(0)[i]));
  }
```
Note that `ASS_LIST` also takes care of setting the length.

**Comment by jesselansdown** [comment]
Hi @fingolfin, sorry, I only just noticed this! Thanks for the advice, I will go through and make  some changes when I get the chance.

**Comment by jesselansdown** [comment]
Ok, I've changed SET_ELM_PLIST to ASS_LIST as you suggested. Thanks again for bringing this to my attention!
